spring:
  jpa:
    properties:
      jadira.usertype.autoRegisterUserTypes: true

MONGO_HOST: localhost
MONGO_PORT: 27017
MONGO_USERDB: admin
MONGO_DATABASE: sprout

management: 
  context-path: /manage
  security:
    role: SUPERUSER

github:
  client:
    clientId: CHANGE_ME
    clientSecret: CHANGE_ME
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    scope: user:email
  resource:
    userInfoUri: https://api.github.com/user
    
linkedin:
  client:
    clientId: CHANGE_ME
    clientSecret: CHANGE_ME
    accessTokenUri: https://www.linkedin.com/oauth/v2/accessToken
    userAuthorizationUri: https://www.linkedin.com/oauth/v2/authorization
    clientAuthenticationScheme: form
    scope: r_basicprofile r_emailaddress
  resource:
    userInfoUri: https://api.linkedin.com/v1/people/~:(email-address,first-name,last-name,location,industry)?format=json